name: Publish Storybook
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup packages
        run: yarn
      - name: Build storybook
        run: yarn run build-storybook
      - run: git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: git config --global user.name "$GITHUB_ACTOR"
      - name: Deploy storybook
        run: yarn run deploy-storybook -r "https://$GITHUB_TOKEN@github.com/ourzora/nft-components.git"
