name: Publish Storybook
on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
  steps:
    - name: Setup repo
      uses: actions/checkout@v2
    - name: Yarn install
      uses: CultureHQ/actions-yarn@master
      with:
        args: install
    - name: Build storybook
      uses: CultureHQ/actions-yarn@master
      with:
        args: run build-storybook
    - name: Deploy storybook
      uses: CultureHQ/actions-yarn@master
      with:
        args: run deploy-storybook
